@Metalhead.Examples.Hosting.CB.Api_HostAddress = http://localhost:5267

GET {{Metalhead.Examples.Hosting.CB.Api_HostAddress}}/weathersettings/
Accept: application/json

###

GET {{Metalhead.Examples.Hosting.CB.Api_HostAddress}}/weatherforecastdata/
Accept: application/json

###

GET {{Metalhead.Examples.Hosting.CB.Api_HostAddress}}/weatherforecastdata/2
Accept: application/json

###